AttendanceFe/Controllers/SubjectGPCController.cs
using Grpc.Net.Client;
using Microsoft.AspNetCore.Mvc;
using AttendanceFe.Protos;
using AttendanceFe.Models;
using AttendanceFe.Models.Request;

namespace AttendanceFe.Controllers
{
    public class SubjectGPCController : Controller
    {
        private readonly SubjectRPC.SubjectRPCClient _subjectRPCClient;

        public SubjectGPCController()
        {
            var channel = GrpcChannel.ForAddress("https://localhost:5095");
            _subjectRPCClient = new SubjectRPC.SubjectRPCClient(channel);
        }

        public async Task<IActionResult> SubjectDetail()
        {
            var response = await _subjectRPCClient.GetAllSubjectsAsync(new Empty());

            var subjectListViewModel = response.Subjects.Select(subject => new SubjectResponse
            {
                Id = subject.Id,
                Code = subject.Code,
                Name = subject.Name,
                NumberSlot = subject.NumberSlot
            }).ToList();

            return View(subjectListViewModel);

        }

        public async Task<IActionResult> Create(sRequest subjectRequest)
        {
            try
            {
                var gpcRequest = new SubjectRequestAdd
                {
                    Code = subjectRequest.Code,
                    Name = subjectRequest.Name,
                    NumberSlot = subjectRequest.NumberSlot
                };

                var response = await _subjectRPCClient.CreateSubjectAsync(gpcRequest);
                Console.WriteLine("CreateSubjectAsync response: " + response.ToString());

                return RedirectToAction("/Home/SubjectDetail");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Đã xảy ra lỗi khi tạo môn học: " + ex.Message);
                return View(subjectRequest);
            }
        }


    }
}

AttendanceFe/Views/SubjectGPC/Create.cshtml
@model AttendanceFe.Models.Request.sRequest

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Subject</h4>
<hr />
<div class="row">
    
        <div class="col-md-4">
            <form asp-controller="SubjectGPC" asp-action="Create">
                <div class="form-group">
                    <label asp-for="Code" class="control-label"></label>
                    <input asp-for="Code" class="form-control" />
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NumberSlot" class="control-label"></label>
                    <input asp-for="NumberSlot" class="form-control" />
                    <span asp-validation-for="NumberSlot" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
   
</div>

<div>
    <a asp-action="/Home/SubjectDetail">Back to List</a>
</div>